jimsalterjrs/sanoid

- sanoid.spec
- syncoid
Added -sshkey arg to to syncoid for unattended cron jobs. Adjust $sshcmd based on presence of the key.
> Added -sshkey arg for automated cron runs

- syncoid
ssh port can be set by passing the -sshport variable on the command line or by changing the $sshport variable.
> Added options to set ssh port.

- sanoid
This adds a --quiet arg.  Helpful when running every minute in cron.
> Adding --quiet arg

- syncoid
I just find out there are some extra sudo execute under root,
minor fix.
> added missing isroot args

- syncoid
This PR is goes with the discussion in #99.  Let me know if there's any changes I need to make.
> Add -o option to syncoid

- sanoid
As discussed in #113. I didn't notice any problems during last week, so here's the PR!
> Fix off-by-one error causing too many snapshots under certain conditions

- syncoid
Updated $sshoption parsing to allow multiple options.
> Multiple option (-o) passing to syncoid

- syncoid
These are the ones that have affected me personally, could probably expand to other places
> Added some extra information to error messages concerning the filesystem they refer to

- CHANGELIST
- FREEBSD.readme
- INSTALL
- LICENSE
- README.md
- debian/rules
- findoid
- sanoid
- sanoid.conf
- sanoid.defaults.conf
- sleepymutex
- syncoid
next try :-) i looked through all the open pull requests and they all need to be rebased, so maybe we can remove the whitespaces now, but i am also fine to do it later.
> removed trailing whitespace

- README.md
- syncoid
> support excluding datasets from replication with a regular expression

- packages/debian/changelog
updated debian changelog with the current CHANGELIST
Fixes #223
> updated debian changelog

- sanoid
some error checking around #165
> check for emtpy lockfile

- sanoid
Added a quiet check for two non-controllable INFO prints
Fixes: #182
> Made two INFO prints mutable

- README.md
- syncoid
> add lz4 compression

- README.md
- syncoid
This PR will recreate clones on the target if possible on initial sends.
Fixes #49
> replicate clones

- README.md
> added all available syncoid/sanoid parameters to README

- sanoid
> show warning if a key is ignored from a template

- README.md
- syncoid
I needed a way to compress as much as possible, since I want to push a snapshot over a slow link (1MB/sec upload). So I added xz compression. I tested it here already, works pretty well.
> Add xz compression

- sanoid
> fixed a regression which causes perl warnings

- sanoid
- sanoid.defaults.conf
> made time units case insensitive and removed monthlies

- syncoid
Add new option: _--mbuffer-size_ which allows one to pass a custom buffer size value to mbuffer(1)
> syncoid: add '--mbuffer-size' option

- syncoid
> added bwlimit units

- syncoid
> check if ssh connection works

- syncoid
> fix unitialized variable

- sanoid
> only list filesystems and volumes

- syncoid
> Catch some errors

- syncoid
> removed debug output from excludes loop

- INSTALL.md
- packages/rhel/sanoid.spec
> fix centos package name

- syncoid
- tests/syncoid/5_reset_resume_state/run.sh
- tests/syncoid/6_reset_resume_state2/run.sh
This PR has some fixes for FreeBSD so all syncoid tests work.
> some FreeBSD related fixes

- sanoid
> remove 's in monitoring messages

- findoid
this also shows the current file version if available
> also show current file version if available

- sanoid
> fixed missing ;

- INSTALL.md
> instruct to use the latest stable release instead of master

- README.md
- syncoid
> implemented option for keeping sync snaps

- sanoid.conf
> document the atomic way to take snapshots recursively

- INSTALL.md
- README.md
> added cron setup example

- README.md
> fix typo in argument description

- sanoid.defaults.conf
> added note about capacity limit overriding

- syncoid
> fix iszfsbusy check for similar dataset names

- syncoid
> check for an invalid argument combination

- INSTALL.md
> added note for busybox based distributions

- README.md
I always forget to look at Wiki because so many projects have nothing there. Found great notes there and link from README.md would help others.
> Add Link to Wiki Detailing sanoid.conf Settings

- syncoid
> fix snapshot listing fallback

- README.md
A minor docs fix in the README.
> Fix missing t on target

- README.md
- syncoid
This is the feature I was talking about in #488 and #477.
I am open to suggestions on the name of the option. (And on the code)
> Add target snapshot deletion.

- syncoid
- tests/syncoid/9_preserve_properties/run.sh
> escape property key and value pair in case of property preservation

- syncoid
> prevent destroying of root dataset which leads to infinite loop
