jimsalterjrs/sanoid

syncoid

This is a simple change which speeds up Sync process on systems with a high amount of Snapshots. It gets only Snapshots desired for the targeted FS and reduces output and thus Parsing time of the get command in the first place, and schould greatly reduce later processes (sorting arrays, mathing snaps) due to the reduced overhead.

Speed-up Sync process

---

syncoid

this one reduces depth of the get command to 1 so zfs get wont pull subsequent dataset snapshots.

didnt grab the right one 1st time

---

sanoid
syncoid

When checking the currently running processes for zfs send & receive activity, also check the `recv` alias.

Also check for 'zfs receive' alias

---

sanoid
syncoid

Hopefully fixes #17 without the need for OS compatibility checking. Tested `ps` options on SmartOS, Ubuntu 14.04, and FreeBSD 10.2. The FreeBSD man page does not document the '-A' option, but the binary supported it with identical output.

Use UNIX-style 'ps' options everywhere for compatibility

---

syncoid

This fixes #58.
Syncoid should do `zfs list -t filesystem` to get only child filesystems regardless of other pool settings.

List only filesystems when finding children

---

syncoid

getsnaps not working when dataset name contains 'creation'

Bug correction in 'getsnaps'

---

syncoid

Exit codes > 256 are treated by bash as `exit_code % 256`, which is confusing. Furthermore, using code 256 is particularly problematic, as 256%256=0, which means success, and is not was was intended here.
For further information about special exit codes, see http://tldp.org/LDP/abs/html/exitcodes.html.

Fix #91: do not use exit codes > 255

---

INSTALL

In v1.4.6 Xenial and newer FreeBSD changes was added.
Change INSTALL to reflect them so it cannot mislead users about requirements.

Update INSTALL to reflect crypto changes

---

sanoid.spec

This pull request bumps the version number within the rpm spec file, additionally it introduces the addition of systemd timers. This is convenient because it means the user can activate sanoid out of the box via "systemctl enable sanoid.timer".
By default the timer is set to run every minute, but this can be overridden by copying the unit and timer into /etc/systemd/system and making the appropriate changes.
The systemd timers are entirely optional within the spec itself, they can be toggled on/off with the _with_systemd variable.

Update RPM Spec

---

README.md

remove --verbose from README.md as syncoid does not support it

remove reference to syncoid --verbose

---

syncoid

Yeah, missed some compression variables for a remote source
Renamed the main compress hash to make it clearer it's not an argument variable, and fixed the broken variables

Helptext syncoid, take 2

---

syncoid

This patches will escape all filesystem names, snapshot names and remote ssh commands as necessary to support all the characters which are allowed in ZFS to be used/supported for syncoid.
Furthermore several regular expression were adapted to ignore any meta characters in filesystem/snapshot names.
Fixes #40

special char fixes

---

syncoid

Follow up to #176 
- The snapshot target for incremental sync's will now also be escaped
- The snapshot list creation properly parses the snapshot in case the name contains a whitespace (match tab character as delimiter for the zfs output)
So this works now:
```
$ zfs create ssd/test/src
$ zfs snapshot ssd/test/src@"spa ce"
$ zfs snapshot ssd/test/src@"spa ce " # tricky space at the end
$ zfs snapshot ssd/test/src@"spa ce "$'\t' # TAB character is luckily not allowed for snapshot name
cannot create snapshot 'ssd/test/src@spa ce     ': invalid character '  ' in name
$ zfs list ssd/test/src -r -t snapshot
NAME                   USED  AVAIL  REFER  MOUNTPOINT
ssd/test/src@spa ce      0B      -   192K  -
ssd/test/src@spa ce      0B      -   192K  -
$ ./syncoid --debug --no-sync-snap …
```

special char fixes #2

---

FREEBSD.readme
INSTALL

Also, recommend installing mbuffer on FreeBSD systems when remote user
is using bourne compatible shell.
Documents jimsalterjrs/sanoid#213

Document compatibility with (t)csh shells

---

syncoid

If syncoid is instructed to skip snapshot creation with the '--no-sync-snap' it shouldn't attempt to prune existing ones (probably from other syncoid invocations to other targets).
Fixes #196

skip pruning with --no-sync-snap

---

sanoid
syncoid

column fields from the zfs output can contain spaces, but the current code splits columns by spaces so in this cases it breaks. The zfs output actually uses tab symbols to split the columns, so use it for parsing too.
Fixes #236

correctly parse zfs column output (space can be included in the values)

---

syncoid

Available in all major distros with a simple yum/apt-get/pkg.
References: 
ZSTD Compression by Allan Jude - https://www.youtube.com/watch?v=hWnWEitDPlM
Zstandard - https://facebook.github.io/zstd/

Added support for ZStandard compression.

---

syncoid

syncoid does not have verbose option. Replace verbose with version in
options list of helptext.

syncoid: fix --version in options list of helptext

---

README.md
packages/debian/sanoid.service
packages/rhel/sanoid.spec

Update readme and systemd unit to use UTC as timezone by default. This will prevent problems with messed up scheduls due the daylight saving times (#155). It's nicer than the current WIP PR #175 which adds a suffix to duplicate snapshots times because of DST hour roll back.
If the user want's to use local time nevertheless (with the documented problem) they can override the systemd unit.
Fixes #155 
Fixed #188

use utc for timestamps as default

---

README.md
sanoid
sanoid.defaults.conf

I just noticed that the monitor-health function doesn't check the capacity, I don't know why I assumed it does but I learnt the hard way that it didn't :-/ If you are okay to check the capacity too for determining the pool health it may be best to make the limit's configurable.
I hard coded some sane defaults for now:
- \>= 80%: Warning (the 80% rule of zfs)
- \>= 95%: Critical

implemented monitor-capacity flag for checking zpool capacity limits

---

sanoid

while pruning snapshots sanoid regenerates the cache file very often (depending on configuration size/dataset count/...). On pools with big number of snapshots and datasets this can be very time consuming (in my case with ~50000 snapshots and ~230 datasets a single regeneration takes ~50 seconds). This PR just removes the destroyed snapshots from the cache file instead of regenerating the whole thing. If another process holds the lock it will defer the update but finally (after all pruning is done) it will wait for the cache update lock and removes all the destroyed snapshots from the cachefile.
For one of my servers this lead to sanoid run time going down from 20-55 minutes to 1-2 minutes.
Fixes #202

cache improvements

---

README.md
syncoid

New option "--skip-parent" for skipping the parent dataset from recursive replication.
Fixes #231

Skip parent

---

syncoid

FreeBSD does not accept options at the end, so without this fix it always fails:
```
$ uname -sr
FreeBSD 11.2-RELEASE
$ /sbin/zfs get receive_resume_token -d 0
cannot open '-d': dataset does not exist
cannot open '0': dataset does not exist
$ /sbin/zfs get -d 0 receive_resume_token
NAME      PROPERTY              VALUE      SOURCE
newzroot  receive_resume_token  -          -
```

Fix 'resume support' detection on FreeBSD

---

syncoid

bring the warning output in line with the following one which warns about the same thing

fixed typo

---

syncoid

currently syncoid only returns non zero in critical error cases (ssh interruptions, zfs errors, ...) where it also will die immediately. In the other cases where it skips datasets for example because they are busy or don't have matching snapshots those are skipped and the process returns no error code.
With this PR it returns non zero exit codes if there was a least one dataset which wasn't replicated because of an error:
1: if zfs was busy or something like that
2: consistent errors like no matching snapshots
Motivation: I use syncoid for remote backups and a only get notified if there was a non zero exit code.

return a non zero exit code if there was a problem replicating datasets

---

syncoid

If there are problem with replication single datasets it shouldn't abort the whole recursive replication but try all and then fail with an failure exit code.
Note: this is based on another PR because it shares some common code, so the former should be merge first
Requires/Based on PR: #249 
Fixes #240

continue recursive replication if some datasets fail

---

syncoid

Should fix #132
I'm unsure about how you want to handle these prints in `monitor_health()` and `monitor_snapshots()`:
```
sanoid:93:      print "$message\n";
sanoid:173:     print "$msg\n";
```

--quiet is not quiet

---

README.md
syncoid

I had a use case where I _do not_ wish to backup large / scratch datasets, but I _do_ wish to backup the tree that they are in.
To skip a dataset, set `syncoid:no-sync` to `true`:
```
zfs set syncoid:no-sync=true tank/users/attie/scratch
```
You can subsequently backup `tank/users` without including `tank/users/attie/scratch`.

added ability to skip datasets... simply set syncoid:no-sync=true

---

sanoid
sanoid.defaults.conf

For example:
```
[sanoid-test-0]
use_template = production
recursive = yes
[sanoid-test-0/var/lib/docker]
use_template = production
skip_children = yes
[sanoid-test-0/var/lib/docker/special]
use_template = production
[template_production]
hourly = 20
daily = 0
monthly = 0
yearly = 0
autosnap = yes
autoprune = yes
[template_ignore]
hourly = 0
daily = 0
monthly = 0
yearly = 0
autosnap = no
autoprune = yes
```
Fixes #296

implemented support for excluding children of a specific dataset

---

packages/rhel/sanoid.spec

Adds a Requires for the perl-Config-IniFiles to the spec file so it will be installed, otherwise sanoid will fail at runtime.

Add dependecy for the configini package

---

INSTALL

The Freebsd package name has a minor typo.

INSTALL: Fix name p5-Config-Inifiles -> p5-Config-IniFiles

---

sanoid
sanoid.defaults.conf

Unused space is wasted space :-) With this PR a new option is introduced where one can defer any pruning of snapshots if less capacity is used as specified.
As this adds a new value, we probably want the default configuration version check from #157 before that.

added option to defer pruning based on the available pool capacity

---

sanoid

I am only using monthly snapshots and would like to use `--monitor-snapshots` to ensure operation. Below shows my config:
```
[tank/Backup]
use_template = backup
#############################
#############################
[template_backup]
hourly = 0
daily = 0
monthly = 6
yearly = 0
autosnap = yes
autoprune = yes
[template_replica]
hourly = 0
daily = 0
monthly = 8
yearly = 0
autosnap = no
autoprune = yes
```
However, `--monitor-snapshots` fails with:
```
CRIT: tank/Backup has no daily snapshots at all!, CRIT: tank/Backup has no hourly snapshots at all!
```
In this case, I would expect to not have daily or hourly snapshots. This PR fixes the above by skipping checks for snapshot types where the number of snapshots is 0 (or negative - I wasn't sure if that was a valid use case).

Ignore snapshots types that are set to 0.

---

sanoid
sanoid.conf
sanoid.defaults.conf

implements pre/post script execution for snapshot creation. This replaces the PR #193 which was cherry picked, this pr adds:
- commit from @darkbasic for providing the snapshot name to the scripts
- timeout logic for the scripts so the can't hang sanoid forever
- cleanup of environment in any script error case
I still need to restructure the code a bit, make the timeout configurable and add documentation.
Fixes #105

add pre, post and prune snapshot scripts

---

sanoid

In my case, I have "frequently" key values in the config, but the release version doesn't support them but they are iterated and used which leads to perl warnings about uninitialized values. So just skip processing unknown interval types.

ignore unknown interval type to prevent perl warnings

---

syncoid
tests/syncoid/1_bookmark_replication_intermediate/run.sh
tests/syncoid/2_bookmark_replication_no_intermediate/run.sh
tests/syncoid/run-tests.sh

If no matching snapshots are found for replication, syncoid will now check for matching bookmarks on source with snapshots on the target (oldest first). If found there are two cases:
* no-stream: direct replication to latest snapshot
* stream: replication to next successor of bookmarked snapshot, after that ordinary replication with intermediate snapshots as bookmark sync doesn't support intermediates
I didn't test yet what happens on system where zfs bookmarks are not supported but it should just silently ignore that and show the ordinary sync error. In the case only the target doesn't support bookmarks, there will be a sync error with the bookmarks.
I also added two tests which I used for testing/developing this feature. They can be safely ran without the need of a vm (no time mangling, …

implemented support for zfs bookmarks as fallback

---

README.md
syncoid

This PR is designed to implement #139. It adds a `--no-privilege-elevation` option that bypasses the root check on both the source and destination. If you want, I can add separate control of the source and destination checks, or rename the option to something else.

Add '--no-privilege-elevation' option to bypass root check.

---

sanoid

For me sanoid runtime is down by 1/3 with a small count of datasets and the difference will only get larger for a higher dataset count.
I don't see any problem if there are snapshots with the same creation time, in the typical use case the snapshots grouped by interval type won't have the same creation time and even if the will get the same creation time anyhow it shouldn't break anything.
But maybe I overlooked something, I will run this on several machines and check if anything comes up.

removed sleeping between snapshot taking

---

README.md
syncoid
tests/syncoid/3_force_delete/run.sh

"--force-delete" flag will instruct syncoid to destroy target datasets which don't have matching snapshots/bookmarks so replication works.
Note: this is bases on another PR because it shares some common code, so the former should be merge first
Requires/Based on PR: #247
Fixes #86

force delete flag

---

sanoid

Allows the user in the config to specify to use zfs snapshot recursion option other than using Perl to recursively take snapshots. So your config would look like 
############################################
[pool4/zones/zone1]
use_template = production
recursive = zfs
[pool4/zones/zone2]
use_template = production
recursive = yes
zone1 would use use zfs recursion and zone2 would use Sanoid's way.
Zone1 recursive snapshot would look like: /sbin/zfs snapshot -r pool4/zones/zone1@autosnap_2017-12-19_15:37:21_hourly ....

Zfs Recursion

---

sanoid

Reverts jimsalterjrs/sanoid#181
Feature changes `recursive` from a toggle (boolean) argument as processed in `init()` to a three-states-possible argument.
In its current condition, datasets without `recursive` set at all cause a failure due to use of uninitialized value in the regex on line 866.

Revert "Zfs Recursion"

---

tests/common/lib.sh

The long test still failed on FreeBSD, this PR fixes the reason and also some codestyle issues with the last commit.

FreeBSD sed needs a different syntax

---

syncoid

This is a follow up PR for #295 which should make providing advanced send/recv options work in all cases syncoid handles (resumeable transfers, bookmark replication, ...).
All the arguments are parsed and before each zfs send/receive only parameters which are valid for the specific use case are whitelisted and injected.
This way one should be able to properly use:
* raw sends
* large block support
* preserve compression
* override properties on receive
* ...

implemented parsing of provided zfs send/recv options and whitelisting for each use case as needed

---

syncoid

Fixes #323
It just uses the no clone replication as fallback if clone creation fails. In the future I would like to do this with proper clone creation handling and detection code so every clone is recreated if possible.

use ordinary replication if clone recreation fails

---

README.md
syncoid

implemented creation of zfs bookmarks

---

INSTALL.md

`sanoid-prune.service` is not referenced by a timer, so I have removed it.
I also modified the behavior of sanoid.service so it will take and prune snapshots according to the config file:
- `--cron` switch is required for it to take action as a service
- `--verbose` is there so that useful logs appear under `journalctl -t sanoid` (I personally run `--debug`)

Fix systemd service definitions.

---

INSTALL.md

This PR reverts #365 which removed the sanoid-prune.service from the install instruction.
@danielewood It is not referenced by a timer but it's referenced by the main sanoid.service and is run afterwards. For an explanation why this is a better approach see this PR #287.
I kept the --verbose flag as it's useful for journald logging.

Revert #365

---

syncoid

fixed ordering of snapshots with the same creation timestamp

---

INSTALL.md
packages/debian/sanoid-prune.service
packages/debian/sanoid.service

The `sanoid-prune.service` never runs after `sanoid.service`.
Declare a `Wants` dependency, and `Before` condition on `sanoid-prune.service` in the sanoid unit, and prune is run after 'sanoid.service'.
The `WantedBy` condition currently in the `sanoid-prune.service` unit will not apply to oneshot units in the way required because conditions in the install section are only applied upon enable/disable.
From [systemd.unit](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#%5BInstall%5D%20Section%20Options) `[Install]` Section Options
> Unit files may include an "[Install]" section, which carries installation information for the unit. This section is not interpreted by systemd(1) during runtime; it is used by the enable and disable commands of the systemctl(1) tool during …

Declare that sanoid service 'Wants' sanoid-prune

---

INSTALL.md

@phreaker0,
I found that on my systems(CentOS7), sanoid-pune.service did nothing until I enabled it. Once I did that, it was called by sanoid.service.
References #367

Added line to enable sanoid-prune.service

---

syncoid

Fixes #396
This PR will only capture the stdout of some replication commands and leave stderr mostly untouched so pv works correctly because it's directly connected to the terminal. The zfs receive command stderr is therefore redirected to stdout for parsing.
The problem arises with zfs send, where stderr can't be redirected to stdout or else the replication stream is contaminated. There is currently only one case where and error check of zfs send is needed (resumed send where the src initial snapshot is missing) but for that case a workaround is used, exploiting that send estimation doesn't work there, we don't need pv output and therefore can capture stderr there. So this PR should fix the interactive output with PV without reverting the error detection stuff, yeah!

Fix interactive output

---

syncoid

The `--sshkey` option specifies the ssh key, *not* the ssh public key.  Empirically, it fails if you point it at a public key and works if you point it at the private part.  Make sense since it's being used as the arg to `-i` in the `ssh` command line.

Documentation buglet, --sshkey specifies the *key*

---

syncoid

This methods doesn't use ugly regexes like it's suggested in #172 but it let's zfs also output the type of object and discards lines which are not related to snapshots. The fallback is only used if the old listing implementation throws an error.
@Will-Moshe please test this on an solaris box
Fixes #172

implemented fallback for listing snapshots on solaris

---

packages/debian/control

The debian package ships with a systemd timer unit but can still be usefull on systems without systemd
This reverts commit 59e181e61d2e0d9f29834fc65b2201f75d1490a4.
Fixes #469

Revert "Depend on systemd"

---

syncoid

If the source dataset dissappeared before we were able to get the
sanoid:sync property, do not set an error exit code.  Handle this
gracefully as this should not be considered an error.
Fixes #380

Gracefully handle error when source dataset disappeared

---

findoid

This solves issues when having intermediate datasets for organisation purposes which aren't mounted.

improve dataset detection by only including mounted datasets

---

findoid

Relates #393 
I don't think backward compatibility is needed here (PATH patching) as this tool isn't scheduled by cron.

don't use hardcoded paths (findoid)

---

findoid

currently if the requested file doesn't exist in an snapshot a lot of perl errors will end up in the output. This patch handles the error properly.

handle FileNotFound errors properly

---

syncoid

pv has options which may be relevant for using syncoid in a script "-n" or for adding  or removing some of the display.
Default value set to what the defaults are for pv if no option is given according to pv manpage.
Specifically here, I implemented this so I could use the "-a" option to add the average transfer rate to the progress.

add ability to configure pv in syncoid

---

syncoid

Removed errant A in zfs list command line arguments.
Fixes #480

Fixed Typo in arguments.

---

packages/debian/postinst

fix debian postinst in the case of non existing legacy cache file

---

syncoid

As it stands, syncoid does not allow ssh targets that do not specify a user. This patch adds that feature, requiring several changes to its behavior:
1. We bring the behavior of syncoid into line with the documentation, which suggests that `:`, rather than `@`, is required when specifying a remote dataset.
2. The behavior of a TARGET or SOURCE that begins with `:` is altered to allow for local dataset names with colons in them.
3. The name of the control socket is changed slightly.
I've been using a version of this patch for around a year. I'm currently using it (rebased onto v2.0.1). The patch also includes a note in the help describing the change.

Do not require user to be specified for syncoid

---

syncoid

Running more than one 'syncoid' at the same time to the same host resulted in two jobs referencing the same socket.
Often results in "already exists, disabling multiplexing" but has in more than one occasion failed with the following:
ControlSocket /tmp/syncoid-zfsbackup-zfsbackup@10.0.0.1-1649107066 already exists, disabling multiplexing
lzop: Inappropriate ioctl for device: <stdin>
CRITICAL ERROR: ssh     -S /tmp/syncoid-zfsbackup-zfsbackup@10.0.0.1-1649107066 zfsbackup@10.0.0.1 ' zfs send  -I '"'"'pool/office'"'"'@'"'"'autosnap_2022-04-04_21:00:00_frequently'"'"' '"'"'pool/office'"'"'@'"'"'autosnap_2022-04-04_21:15:00_frequently'"'"' | lzop  | mbuffer -R 5m -q -s 128k -m 16M 2>/dev/null' | mbuffer  -q -s 128k -m 16M 2>/dev/null | lzop -dfc | pv -s 18356312 |  zfs receive  -s -F …

append a rand int to the socket name.

---

INSTALL.md

Add requirement for syncoid w/ remote hosts to be able to sudo without a password.
Recommends a least privilege configuration option for enabling `NOPASSWD`

Include syncoid remote user requirement

---

INSTALL.md

Previous instructions couldn't actually be copied and pasted. This will update the instructions to work correctly when copied as-is

Update debian installation instructions

---

INSTALL.md

Updated the install language, and commands, to better server Centos 8 and it's derivatives. Instead of using CPAN, enabling the 'PowerTools' repo will make those modules available for installation and kept current with normal OS updates.
Updated command to enable _and_ start sanoid.timer, instead of using two commands.

Update Install.md for Centos 8

---

INSTALL.md

Add requirement for syncoid w/ remote hosts to be able to sudo without a password.
Recommends a least privilege configuration option for enabling `NOPASSWD`
I created this PR to fix a previous PR that seems to have lost support from the original author: https://github.com/jimsalterjrs/sanoid/pull/670

Include syncoid remote user requirment

---

syncoid

this brings back the --no-rollback option without reverting to the old way of explicit rolling back the target filesystem.
The option is very useful to others (https://www.reddit.com/r/zfs/comments/xcffnn/syncoid_norollback_option_gone/) and me.

bring back no-rollback option

---

syncoid

previously the following scenario
host1: pool1 --- syncoid over ssh ---> host2: pool1
host2: pool1 --- syncoid local --------> host2: backup/pool1
would fail if run concurrently, because the zfs receive check wouldn't differentiate between "pool1" and "backup/pool1"

improve accuracy of zfs receive check

---

README.md

Since it is possible people might use different compression options on the destination dataset, it seems helpful to clarify this option is for the wire transfer, not overriding destination compression.

Clarified that compression is on the wire

---

README.md
syncoid
tests/syncoid/8_force_delete_snapshot/run.sh

the following scenario will work with this PR:
```
zfs create pool/dataset
zfs snapshot pool/dataset@duplicate
syncoid pool/dataset pool/dataset2
zfs destroy pool/dataset@duplicate
zfs snapshot pool/dataset@duplicate
syncoid --force-delete pool/dataset pool/dataset2
```

implemented removal of conflicting snapshots with force-delete option

---

sanoid

don't try to parse stats for spares which are in use as there are none

---

syncoid

I implemented the support to use the `-F` ssh client argument. This allows using a custom `ssh_config(5)` file, which my setups rely on heavily. Tested working :)

Implementing support for ssh_config(5) files

---

packages/rhel/sanoid.spec

- 11/24/2020 -> Tuesday
- 12/04/2018 -> Tuesday
Prior to changes:
```
$ rpmlint sanoid.spec
sanoid.spec: E: specfile-error warning: bogus date in %changelog: Wed Nov 24 2020 Christoph Klaffl <christoph@phreaker.eu> - 2.1.0
sanoid.spec: E: specfile-error warning: bogus date in %changelog: Wed Dec 04 2018 Christoph Klaffl <christoph@phreaker.eu> - 2.0.0
0 packages and 1 specfiles checked; 2 errors, 0 warnings.
```
After changes:
```
$ rpmlint sanoid.spec
0 packages and 1 specfiles checked; 0 errors, 0 warnings.
```

Fix bogus dates in %changelog to satisfy rpmlint

---

INSTALL.md

This commit aims to make the "CentOS" documentation a bit less CentOS-specific (the steps for proper RHEL are slightly different), and adds the missing `perl-Getopt-Long` dependency and documents the dependency on PowerTools/CodeReady repos to pull the packages containing these Perl modules.

Improve documentation for RHEL-family distros

---

INSTALL.md

Installation information for running sanoid on MacOS via launchd. A launchd example plist file is provided in the same way equivalent files are created on other platforms.
I've been running sanoid for this way for a few days. The main advantages are the better integration into MacOS's timers, in particular that sanoid will be invoked once after waking up from sleep, if an event was missed.

MacOS Install Information

---

syncoid

uses the same counter approach as with the snapshot listing to preserve the correct order from the zfs output

support bookmarks which are taken in the same second

---

sanoid

leading and/or trailing spaces in the config values will lead to weird issues which are hard to track down, so trim them to get rid of those cases.
Fixes #834

trim config values

---

syncoid

'D' is deprecated and only there for backward compatibility
'V' updates the process title with states
'X' 's' is for excluding datasets and skipping missing snapshots with 'R'
'b' seems to be new
Fixes #805

update possible zfs send options

---

syncoid

Some of the regexes to detect lines containing the `creation` or `guid` property also select lines where the snapshot / bookmark name contains either `creation` or `guid`. Fixed by requiring a tab right before `creation` or `guid`.
Note that I've only specifically tested this issue for snapshots, though from the code it seems obvious that the same bug applies to bookmark as well, hence also changed those regexes as as well.
Fixes #858

fix "creation"/"guid" regex detection

---

syncoid
tests/syncoid/7_preserve_recordsize/run.sh
tests/syncoid/9_preserve_properties/run.sh

Some syncoid tests and the "--preserve-properties" flag are failing on ZoL/ZoF devices with the following test errors:
```shell
DEBUG: getting locally set values of properties on syncoid-test-9/src/zvol16...
zfs get all -s local -H 'syncoid-test-9/src/zvol16'
WARNING: getlocalzfsvalues failed for syncoid-test-9/src/zvol16: cannot open '-s
': dataset does not exist
cannot open 'local': dataset does not exist
cannot open '-H': dataset does not exist
``` 
```shell
+ zfs get recordsize -t filesystem -r syncoid-test-7/dst
cannot open '-t': dataset does not exist
cannot open 'filesystem': dataset does not exist
cannot open '-r': dataset does not exist
``` 
Fixed by moving the property field directly before the dataset for zfs-gets in the affected files. This mimics how zfs-get is used …

fix zfs-get for "--preserve-properties" and tests

---

packages/debian/control

The package produced by ZFS 2.2.0 `make native-deb-utils` is called `openzfs-zfsutils`.

debian: add openzfs-zfsutils as an alternative to zfsutils-linux

---

sanoid

Based on text in the issue https://github.com/jimsalterjrs/sanoid/issues/851, these code changes will make `sanoid` skip an update of the cache file, even if it has expired, if the following logic conditions are all met:
- The commands passed to `sanoid` include a `--monitor-*` command; and
- **No** command that takes a snapshot or prunes a snapshot are supplied.
Fixes jimsalterjrs/sanoid#851

Fixes jimsalterjrs/sanoid#851

---

syncoid

Some errors weren't automatically handled if snapshots were filtered

handle error output for filtered replications

---

syncoid

I've noticed that during Syncoid runs when using the `--delete-target-snapshots` and `--no-sync-snap` flags, there are issues with zfs rolling back snapshots during a sync. 
The sync workflow looks something like this:
- Initial start
- Source: snap1, snap2
- Target: 
- Sync snapshots to Target, take new snapshot on Source, delete snapshot on Source that isn't newest
- Source: snap1, snap3
- Target: snap1, snap2
- Error occurs here when trying to run a subsequent sync as the `%snaps` are cached from before the rollback, but during the sync the snapshots are rolled back to the latest common and then `%snaps` contains snapshots to be deleted that no longer exist
```output
root@target ~
NEWEST SNAPSHOT: snapshot-snap2
Removing target/ubuntu because no matching snapshots were found
NEWEST …
```

fix(syncoid): regather $snaps on --delete-target-snapshots flag

---

findoid

currently relative paths won't work properly with findoid. this pr resolves the relative path to a canonical one to make it work.

[findoid] support relative paths

---

syncoid

Add the zstdmt-fast and zstdmt-slow compress options to allow use of multithreading when using zstd compression.

syncoid: Add zstdmt compress options

---

sanoid

- list of target datasets will be cached like the snapshot cache
This is critical for the monitor commands in case those are executed in a very fast interval. In case of recursive options sanoid needs to build a list of target datasets by invoking zfs list for each configured parent dataset which can take a while depending on the hardware and count of datasets configured.
For example for one of my servers:
```
OK ZPOOL rpool : 72%, OK ZPOOL storage : 4%, OK ZPOOL bpool : 33%
real    0m0.266s
user    0m0.228s
sys     0m0.039s
INFO: dataset cache expired - updating from zfs list.
OK ZPOOL bpool : 33%, OK ZPOOL rpool : 72%, OK ZPOOL storage : 4%
real    0m3.847s
user    0m0.241s
sys     0m3.571s
```
- snaphots are only retrieved if needed for the instructed commands (for example …

[sanoid] implemented dataset cache and fix race conditions

---

syncoid

Fixes #982 
Preserving the encryption property doesn't work in most cases, so blacklist it.

blacklist encryption property from preserving
